# Calculate the p-value cutoffs to use for TF motifs based on how common they are in the genome set we used
This is based on [Townsend et al 2025](https://www.biorxiv.org/content/10.1101/2025.09.12.675852v1)

In [1]:
library(data.table)
library(stringr)
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
res <- fread("/scratch/Users/hoto7260/Resp_Env//Comb_UPM_WSP_ADP/ADP/TFEA/out/NonTSS_ADP_par_rat_Wd_HK_noback/results.txt")
res[1:2,]
colnames(res) <- c("TF", "Escore", "CorrEscore", "Events", "GC", "FPKM", "Padj", "CorrPadj", "MB_LE", "MB_LE_stdev", "SE_LE", "SE_LE_stdev", "Frac", "Na")
res[1:10,]

gene_res <- fread("/scratch/Users/hoto7260/Resp_Env//Comb_UPM_WSP_ADP/ADP/TFEA/out/Gene_ADP_par_rat_Wd_HK_noback/results.txt")

colnames(gene_res) <- c("TF", "Escore", "CorrEscore", "Events", "GC", "FPKM", "Padj", "CorrPadj", "MB_LE", "MB_LE_stdev", "SE_LE", "SE_LE_stdev", "Frac", "Na")
gene_res[1:10,]

Warning message in fread("/scratch/Users/hoto7260/Resp_Env//Comb_UPM_WSP_ADP/ADP/TFEA/out/NonTSS_ADP_par_rat_Wd_HK_noback/results.txt"):
“Detected 13 column names but the data has 14 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.”

  V1                  #TF         E-Score    Corrected E-Score Events    GC
1 ZN362.H12CORE.0.P.C 0.005836104  0.2022343 13588             0.1116749 NaN
2 ZN560.H12CORE.0.P.C 0.007389366 -0.1025688 16755             0.6484448 NaN
  FPKM P-adj  Corrected P-adj MB_LE MB_LE Stdev SE_LE   SE_LE Stdev
1 1    1e-179 1068              NaN 2637            NaN 0.54
2 1     1e-58 1275            66.16 1355        1548.42 0.54
  Frac Abv Null
1 NA
2 NA

   TF                  Escore       CorrEscore  Events GC        FPKM Padj
1  ZN362.H12CORE.0.P.C  0.005836104  0.20223431 13588  0.1116749 NaN  1e+00
2  ZN560.H12CORE.0.P.C  0.007389366 -0.10256878 16755  0.6484448 NaN  1e+00
3  P53.H12CORE.0.P.B   -0.386608574 -0.43341024  1204  0.5377877 NaN  1e-40
4  P73.H12CORE.0.PS.A  -0.324166695 -0.37003816  1340  0.5361579 NaN  1e-30
5  ZN441.H12CORE.1.P.C  0.010520812 -0.08172782 14506  0.6174158 NaN  1e+00
6  P63.H12CORE.0.PS.A  -0.294660768 -0.34300121  1190  0.5404838 NaN  1e-21
7  SP2.H12CORE.1.P.B    0.317590149  0.18609656  3004  0.6861772 NaN  1e-65
8  P73.H12CORE.1.P.B   -0.159032973 -0.20219558  2457  0.5314117 NaN  1e-12
9  P63.H12CORE.1.PS.A  -0.160253183 -0.19266969  2368  0.5125833 NaN  1e-11
10 KAISO.H12CORE.1.P.B  0.229024921  0.14173110  3812  0.6087344 NaN  1e-44
   CorrPadj MB_LE MB_LE_stdev SE_LE SE_LE_stdev Frac Na
1  1e-179    1068     NaN     2637      NaN     0.54 NA
2   1e-58    1275   66.16     1355  1548.42     0.54 NA
3   1e-50   14763   32.58     3489    93.29     0.38 NA
4   1e-39   16232     NaN     4113      NaN     0.42 NA
5   1e-30    1248   52.22     3499    29.93     0.57 NA
6   1e-29   15680   35.00     3951   528.50     0.40 NA
7   1e-22     394   66.50     1302    48.50     0.41 NA
8   1e-21   13944   51.87     2726  1472.78     0.41 NA
9   1e-17   20822 1222.20     2936  1735.75     0.53 NA
10  1e-16     705   21.93     2302    43.52     0.43 NA

Warning message in fread("/scratch/Users/hoto7260/Resp_Env//Comb_UPM_WSP_ADP/ADP/TFEA/out/Gene_ADP_par_rat_Wd_HK_noback/results.txt"):
“Detected 13 column names but the data has 14 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.”

   TF                   Escore       CorrEscore  Events GC        FPKM Padj
1  ZN362.H12CORE.0.P.C   0.011427500  0.18288792 6933   0.1116749 NaN  1.0000
2  ZN613.H12CORE.0.P.C   0.030317541  0.11691591 2582   0.3148209 NaN  1.0000
3  NRF1.H12CORE.0.PS.A  -0.043615554 -0.11087220 2403   0.6831250 NaN  0.5400
4  ZN791.H12CORE.0.P.C   0.057538265  0.18240088  807   0.2232225 NaN  1.0000
5  KMT2A.H12CORE.0.P.B   0.068969890 -0.07602410 3540   0.8692156 NaN  0.0001
6  ZN787.H12CORE.0.M.C   0.191635791  0.19424130  710   0.5158863 NaN  0.0001
7  FOXL1.H12CORE.0.S.B   0.018580540  0.12443003 1455   0.2687369 NaN  1.0000
8  Z585A.H12CORE.0.P.C   0.037247628  0.10672654 1840   0.3558022 NaN  1.0000
9  FOXC2.H12CORE.0.SM.B -0.002185399  0.10478934 1630   0.2660432 NaN  1.0000
10 ZN519.H12CORE.0.P.C   0.041817126 -0.08714912 2029   0.8308478 NaN  1.0000
   CorrPadj MB_LE MB_LE_stdev SE_LE SE_LE_stdev Frac Na
1  1e-73    1817  1632.22      926  566.05      0.56 NA
2  1e-07     407      NaN     2111     NaN      0.52 NA
3  1e-07     996    74.25      941  117.10      0.65 NA
4  1e-05     651    17.24     1316   48.02      0.42 NA
5  1e-05    7332      NaN     2585     NaN      0.44 NA
6  1e-04    2954    18.50     1357   65.00      0.36 NA
7  1e-04    1080     6.50     1086    6.50      0.47 NA
8  1e-04    1077   220.89     1262  815.87      0.43 NA
9  1e-03    1090   868.01      720  583.47      0.53 NA
10 1e-03    8238   718.73     2113  791.40      0.55 NA

In [3]:
dim(res[res$Events > 5000,])
quantile(res[res$Events > 5000,]$Events)
dim(res[res$Events < 700 & res$Events > 0,])
quantile(res[res$Events < 700 & res$Events > 0,]$Events)

too_low <- res[res$Events < 700 & res$Events > 0,]$TF
too_high <- res[res$Events > 5000 ,]$TF
length(too_low)
length(too_high)

[1] 18 14

      0%      25%      50%      75%     100%
 5070.00  5610.25  6514.00 10489.50 17750.00

[1] 132  14

    0%    25%    50%    75%   100%
132.00 509.75 609.00 664.50 699.00

[1] 132

[1] 18

In [4]:
dim(gene_res[gene_res$Events > 7000,])
quantile(gene_res[gene_res$Events > 7000,]$Events)
dim(gene_res[gene_res$Events < 700 & gene_res$Events > 0,])
quantile(gene_res[gene_res$Events < 700 & gene_res$Events > 0,]$Events)

gene_too_low <- gene_res[gene_res$Events < 700 & gene_res$Events > 0,]$TF
gene_too_high <- gene_res[gene_res$Events > 5000 ,]$TF
length(gene_too_low)
length(gene_too_high)

[1]  2 14

     0%     25%     50%     75%    100%
7039.00 7100.75 7162.50 7224.25 7286.00

[1] 763  14

  0%  25%  50%  75% 100%
  89  373  483  586  698

[1] 763

[1] 4

In [5]:
setdiff(gene_too_high, too_high)
only_gene_too_low = setdiff(gene_too_low, too_low)
length(only_gene_too_low)
quantile(gene_res[gene_res$TF %in% only_gene_too_low,]$Events)

character(0)

[1] 640

    0%    25%    50%    75%   100%
 89.00 376.50 492.00 593.25 698.00

In [6]:
quantile(gene_res[gene_res$TF %in% too_high,]$Events)
quantile(gene_res[gene_res$TF %in% too_low,]$Events)

     0%     25%     50%     75%    100%
1247.00 2244.25 3063.00 4364.25 7286.00

   0%   25%   50%   75%  100%
  0.0 367.0 461.5 549.5 886.0

In [7]:
# read in pvalue
pval_file <- fread("/scratch/Users/hoto7260/assets/PVAL_CUTOFF_ESTIMATES_H12.CORE.CUWA.txt")
pval_file[1:3,]
table(pval_file$best_pval)

  MOTIF               best_pval
1 AHR.H12CORE.0.P.B   1e-05
2 AHRR.H12CORE.0.P.C  1e-05
3 ALX1.H12CORE.0.SM.B 5e-06

1e-11 5e-11 5e-10 1e-09 5e-09 1e-08 5e-08 1e-07 5e-07 1e-06 5e-06 1e-05 5e-05
    5     1     4     1    15     6    27    17   100   209   725   205   127
1e-04
    1

In [8]:
table(pval_file[pval_file$MOTIF %in% too_low,]$best_pval)
table(pval_file[pval_file$MOTIF %in% too_high,]$best_pval)

5e-10 1e-08 5e-08 1e-07 5e-07 1e-06 5e-06 1e-05
    1     2     2     4    10    45    42    26

1e-11 1e-09 5e-07 5e-06 5e-05
    2     1     1     5     9

In [16]:
get_less_string_dict <- c("5e-11"="1e-10", "5e-10"="1e-9", "5e-09"="1e-8", "1e-08"="5e-8", "5e-08"="1e-7", "1e-07"="5e-7", 
                          "5e-07"="1e-6", "1e-06"="5e-6", "5e-06"="1e-5", "1e-05"="5e-5", "5e-05"="1e-4")
get_more_string_dict <- c("1e-11"="5e-12", "5e-11"="1e-11", "5e-10"="1e-10", "1e-09"="5e-10", "5e-09"="1e-9", "1e-08"="5e-9", "5e-08"="1e-8", "1e-07"="5e-8", 
                          "5e-07"="1e-7", "1e-06"="5e-7", "5e-06"="1e-6", "1e-05"="5e-6", "5e-05"="1e-5")
# # Convert named vector to numeric
# get_less_string_dict <- setNames(as.numeric(names(get_less_string_dict)), as.numeric(get_less_string_dict))
# get_more_string_dict <- setNames(as.numeric(names(get_more_string_dict)), as.numeric(get_more_string_dict))

pval_file <- pval_file %>%
  mutate(new_best_pval = ifelse(MOTIF %in% too_high, 
                            get_more_string_dict[as.character(best_pval)], best_pval)) %>%
  mutate(new_best_pval = ifelse(MOTIF %in% too_low, 
                            get_less_string_dict[as.character(best_pval)], new_best_pval))


pval_file$new_best_pval <- as.numeric(pval_file$new_best_pval)

pval_file[1:3,]

  MOTIF               best_pval new_best_pval diff
1 AHR.H12CORE.0.P.B   1e-05     1e-05         0e+00
2 AHRR.H12CORE.0.P.C  1e-05     1e-05         0e+00
3 ALX1.H12CORE.0.SM.B 5e-06     1e-05         5e-06

In [17]:
as.character(pval_file$best_pval[1])
get_more_string_dict[as.character(pval_file$best_pval[1])]

[1] "1e-05"

 1e-05
"5e-6"

In [18]:
pval_file$diff = pval_file$new_best_pval - pval_file$best_pval
pval_file[pval_file$MOTIF %in% too_high,]

   MOTIF                 best_pval new_best_pval diff
1  E2F2.H12CORE.0.S.B    5e-05     1e-05         -4e-05
2  E2F4.H12CORE.0.P.B    5e-05     1e-05         -4e-05
3  E2F4.H12CORE.2.S.B    5e-05     1e-05         -4e-05
4  ETS1.H12CORE.0.S.B    5e-05     1e-05         -4e-05
5  KLF12.H12CORE.1.PSM.A 5e-06     1e-06         -4e-06
6  MAD4.H12CORE.0.P.C    5e-05     1e-05         -4e-05
7  RUNX2.H12CORE.1.S.B   5e-05     1e-05         -4e-05
8  SP4.H12CORE.1.S.B     5e-06     1e-06         -4e-06
9  THB.H12CORE.3.S.C     5e-06     1e-06         -4e-06
10 ZBT7B.H12CORE.0.SM.B  5e-05     1e-05         -4e-05
11 ZBT7C.H12CORE.0.S.B   5e-05     1e-05         -4e-05
12 ZN213.H12CORE.0.P.C   5e-06     1e-06         -4e-06
13 ZN362.H12CORE.0.P.C   1e-09     5e-10         -5e-10
14 ZN441.H12CORE.1.P.C   1e-11     5e-12         -5e-12
15 ZN560.H12CORE.0.P.C   1e-11     5e-12         -5e-12
16 ZN730.H12CORE.0.P.C   5e-07     1e-07         -4e-07
17 ZNF8.H12CORE.0.P.C    5e-05     1e-05         -4e-05
18 ZSC21.H12CORE.0.P.C   5e-06     1e-06         -4e-06

In [19]:

pval_file[1:2,]
quantile(pval_file$diff)
quantile(pval_file[pval_file$MOTIF %in% too_high,]$diff)
quantile(pval_file[pval_file$MOTIF %in% too_low,]$diff)

  MOTIF              best_pval new_best_pval diff
1 AHR.H12CORE.0.P.B  1e-05     1e-05         0
2 AHRR.H12CORE.0.P.C 1e-05     1e-05         0

    0%    25%    50%    75%   100%
-4e-05  0e+00  0e+00  0e+00  4e-05

      0%      25%      50%      75%     100%
-4.0e-05 -4.0e-05 -2.2e-05 -4.0e-06 -5.0e-12

   0%   25%   50%   75%  100%
5e-10 4e-06 5e-06 5e-06 4e-05

In [20]:
pval_file[is.na(pval_file$diff),]

     MOTIF best_pval new_best_pval diff

In [21]:
new_pval_file <- pval_file[,c("MOTIF", "new_best_pval")]
colnames(new_pval_file) <- c("MOTIF", "best_pval")

write.table(new_pval_file, 
            "/scratch/Users/hoto7260/assets/PVAL_CUTOFF_ESTIMATES_H12_noback.CORE.CUWA.txt", 
           quote=FALSE, row.names=FALSE, sep="\t")